//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddCalendarAppointment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reminder
    {
        public int ReminderID { get; set; }
        public int AppointmentID { get; set; }
        public string Message { get; set; }
        public System.DateTime ReminderTime { get; set; }
    
        public virtual Appointment Appointment { get; set; }
    }
}
